---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.eu11.hana.ondemand.com"
    cfOrg: "CNHi-d01-ddwxf152"
    cfSpace: "D01-Sp-01"
    cfAppName: "cnh1"
    cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.eu11.hana.ondemand.com"
    cfOrg: "CNHi-d01-ddwxf152"
    cfSpace: "D01-Sp-01"
    cfAppName: "cnh1"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "Q01-MTA"
    credentialsId: "tms-credentials"
